import type { Metadata } from "next";
import { Inter, Space_Mono } from "next/font/google";
import "../styles/globals.css";
import { CartProvider } from "../context/cartContext";

const inter = Inter({ subsets: ["latin"] });

const mono = Space_Mono({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mono.className}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
